server:
  port: 8080
  
spring:
  application:
    name: ORDER-SERVER

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    

    
  
eureka:
  client:
   register-with-eureka: true
   fetch-registry: true
   serviceUrl:
     defaultZone: http://localhost:8761/eureka/
  instance:
    hostname:localhost